# Generated by Django 4.2.7 on 2025-07-15 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import file_management.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('allowed_extensions', models.JSONField(blank=True, default=list)),
                ('max_file_size', models.PositiveIntegerField(default=10485760)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'File Category',
                'verbose_name_plural': 'File Categories',
                'db_table': 'file_categories',
            },
        ),
        migrations.CreateModel(
            name='FileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_file_size_general', models.PositiveIntegerField(default=10485760)),
                ('max_file_size_image', models.PositiveIntegerField(default=5242880)),
                ('max_file_size_video', models.PositiveIntegerField(default=104857600)),
                ('max_file_size_document', models.PositiveIntegerField(default=10485760)),
                ('storage_limit_client', models.PositiveIntegerField(default=1073741824)),
                ('storage_limit_professional', models.PositiveIntegerField(default=5368709120)),
                ('allowed_image_extensions', models.JSONField(blank=True, default=list, help_text='Allowed image file extensions')),
                ('allowed_document_extensions', models.JSONField(blank=True, default=list, help_text='Allowed document file extensions')),
                ('allowed_video_extensions', models.JSONField(blank=True, default=list, help_text='Allowed video file extensions')),
                ('enable_virus_scanning', models.BooleanField(default=True)),
                ('auto_delete_temp_files_days', models.PositiveIntegerField(default=7)),
                ('enable_file_versioning', models.BooleanField(default=True)),
                ('max_file_versions', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'File Settings',
                'verbose_name_plural': 'File Settings',
                'db_table': 'file_settings',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to=file_management.models.user_file_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('archive', 'Archive'), ('other', 'Other')], max_length=20)),
                ('mime_type', models.CharField(max_length=100)),
                ('upload_purpose', models.CharField(choices=[('profile_avatar', 'Profile Avatar'), ('project_image', 'Project Image'), ('portfolio_item', 'Portfolio Item'), ('message_attachment', 'Message Attachment'), ('contract_document', 'Contract Document'), ('proposal_attachment', 'Proposal Attachment'), ('general', 'General')], default='general', max_length=30)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/%d/')),
                ('is_scanned', models.BooleanField(default=False)),
                ('is_safe', models.BooleanField(default=True)),
                ('virus_scan_result', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_temp', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_management.filecategory')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'db_table': 'uploaded_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to=file_management.models.user_file_path)),
                ('file_size', models.PositiveIntegerField()),
                ('change_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='file_management.uploadedfile')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Version',
                'verbose_name_plural': 'File Versions',
                'db_table': 'file_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('download', 'Download'), ('edit', 'Edit')], default='view', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('max_access_count', models.PositiveIntegerField(blank=True, null=True)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='file_management.uploadedfile')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_shared', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Share',
                'verbose_name_plural': 'File Shares',
                'db_table': 'file_shares',
            },
        ),
        migrations.CreateModel(
            name='FileFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('files', models.ManyToManyField(blank=True, related_name='folders', to='file_management.uploadedfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='file_management.filefolder')),
            ],
            options={
                'verbose_name': 'File Folder',
                'verbose_name_plural': 'File Folders',
                'db_table': 'file_folders',
            },
        ),
        migrations.CreateModel(
            name='FileComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_comments', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='file_management.uploadedfile')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='file_management.filecomment')),
            ],
            options={
                'verbose_name': 'File Comment',
                'verbose_name_plural': 'File Comments',
                'db_table': 'file_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('view', 'View'), ('share', 'Share'), ('delete', 'Delete'), ('edit', 'Edit'), ('comment', 'Comment')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='file_management.uploadedfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Activity Log',
                'verbose_name_plural': 'File Activity Logs',
                'db_table': 'file_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='uploaded_fi_uploade_34796d_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['file_type'], name='uploaded_fi_file_ty_206d78_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['upload_purpose'], name='uploaded_fi_upload__fb00a0_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['is_public'], name='uploaded_fi_is_publ_b814b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fileversion',
            unique_together={('original_file', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='fileshare',
            unique_together={('file', 'shared_with')},
        ),
        migrations.AlterUniqueTogether(
            name='filefolder',
            unique_together={('name', 'parent', 'owner')},
        ),
    ]
