# Generated by Django 5.2.4 on 2025-07-16 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('type', models.CharField(choices=[('consultation', 'Consultation'), ('site_visit', 'Site Visit'), ('meeting', 'Meeting'), ('inspection', 'Inspection')], max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_confirmation', models.BooleanField(default=True)),
                ('buffer_time_before', models.PositiveIntegerField(default=0, help_text='Buffer time before appointment in minutes')),
                ('buffer_time_after', models.PositiveIntegerField(default=0, help_text='Buffer time after appointment in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(limit_choices_to={'user_type__in': ['home_pro', 'specialist', 'crew_member']}, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment Template',
                'verbose_name_plural': 'Appointment Templates',
                'db_table': 'appointment_templates',
                'ordering': ['professional', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('break_start', models.TimeField(blank=True, help_text='Lunch break start time', null=True)),
                ('break_end', models.TimeField(blank=True, help_text='Lunch break end time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(limit_choices_to={'user_type__in': ['home_pro', 'specialist', 'crew_member']}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professional Availability',
                'verbose_name_plural': 'Professional Availability',
                'db_table': 'professional_availability',
                'ordering': ['professional', 'weekday'],
                'unique_together': {('professional', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='UnavailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_full_day', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(limit_choices_to={'user_type__in': ['home_pro', 'specialist', 'crew_member']}, on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_dates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unavailable Date',
                'verbose_name_plural': 'Unavailable Dates',
                'db_table': 'unavailable_dates',
                'ordering': ['date'],
                'unique_together': {('professional', 'date')},
            },
        ),
    ]
