# Generated by Django 5.2.4 on 2025-07-18 00:13

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_additional_requirements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_letter', models.TextField(help_text='شرح مفصل عن كيفية تنفيذ المشروع', verbose_name='رسالة العرض')),
                ('amount', models.DecimalField(decimal_places=2, help_text='المبلغ الإجمالي بالدولار', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ المطلوب')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='العملة')),
                ('timeline', models.CharField(help_text='مثل: 2-3 أسابيع', max_length=100, verbose_name='المدة الزمنية')),
                ('estimated_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='الساعات المقدرة')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('withdrawn', 'منسحب'), ('expired', 'منتهي الصلاحية')], default='pending', max_length=20, verbose_name='حالة العرض')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('normal', 'عادي'), ('high', 'عالي'), ('urgent', 'عاجل')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('is_featured', models.BooleanField(default=False, help_text='عرض مميز يظهر في المقدمة', verbose_name='عرض مميز')),
                ('response_time', models.CharField(blank=True, help_text='مثل: خلال ساعة', max_length=50, verbose_name='وقت الاستجابة')),
                ('includes_materials', models.BooleanField(default=False, verbose_name='يشمل المواد')),
                ('warranty_period', models.CharField(blank=True, max_length=50, verbose_name='فترة الضمان')),
                ('portfolio_samples', models.JSONField(blank=True, default=list, verbose_name='عينات من أعمال سابقة')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات')),
                ('client_response', models.TextField(blank=True, verbose_name='رد العميل')),
                ('rejection_reason', models.CharField(blank=True, max_length=255, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرد')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية')),
                ('professional_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='تقييم المحترف')),
                ('professional_reviews_count', models.PositiveIntegerField(default=0, verbose_name='عدد التقييمات')),
                ('professional_completion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='معدل إنجاز المشاريع')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_proposals', to=settings.AUTH_USER_MODEL, verbose_name='المحترف')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'عرض',
                'verbose_name_plural': 'العروض',
                'db_table': 'proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='proposal_attachments/', verbose_name='الملف')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file_type', models.CharField(choices=[('image', 'صورة'), ('document', 'مستند'), ('video', 'فيديو'), ('other', 'أخرى')], default='document', max_length=20, verbose_name='نوع الملف')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم الملف (بايت)')),
                ('description', models.TextField(blank=True, verbose_name='وصف الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments_files', to='proposals.proposal', verbose_name='العرض')),
            ],
            options={
                'verbose_name': 'مرفق العرض',
                'verbose_name_plural': 'مرفقات العروض',
                'db_table': 'proposal_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المرحلة')),
                ('description', models.TextField(blank=True, verbose_name='وصف المرحلة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ المرحلة')),
                ('timeline', models.CharField(max_length=100, verbose_name='مدة المرحلة')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتيب المرحلة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='proposals.proposal', verbose_name='العرض')),
            ],
            options={
                'verbose_name': 'معلم العرض',
                'verbose_name_plural': 'معالم العروض',
                'db_table': 'proposal_milestones',
                'ordering': ['proposal', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProposalView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='proposals.proposal', verbose_name='العرض')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المشاهد')),
            ],
            options={
                'verbose_name': 'مشاهدة العرض',
                'verbose_name_plural': 'مشاهدات العروض',
                'db_table': 'proposal_views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['project', 'status'], name='proposals_project_9eb3ef_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['professional', 'status'], name='proposals_profess_fb481f_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['status', 'created_at'], name='proposals_status_0a3faa_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['is_featured', 'created_at'], name='proposals_is_feat_8b8eec_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['amount'], name='proposals_amount_d58e72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('project', 'professional')},
        ),
        migrations.AlterUniqueTogether(
            name='proposalmilestone',
            unique_together={('proposal', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='proposalview',
            unique_together={('proposal', 'viewer')},
        ),
    ]
