# Generated by Django 5.2.4 on 2025-07-18 01:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_additional_requirements'),
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Proposal', 'verbose_name_plural': 'Proposals'},
        ),
        migrations.AlterModelOptions(
            name='proposalattachment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Proposal Attachment', 'verbose_name_plural': 'Proposal Attachments'},
        ),
        migrations.AlterModelOptions(
            name='proposalmilestone',
            options={'ordering': ['proposal', 'order'], 'verbose_name': 'Proposal Milestone', 'verbose_name_plural': 'Proposal Milestones'},
        ),
        migrations.AlterModelOptions(
            name='proposalview',
            options={'ordering': ['-viewed_at'], 'verbose_name': 'Proposal View', 'verbose_name_plural': 'Proposal Views'},
        ),
        migrations.AlterField(
            model_name='proposal',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount Required'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='attachments',
            field=models.JSONField(blank=True, default=list, verbose_name='Attachments'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='client_response',
            field=models.TextField(blank=True, verbose_name='Client Response'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='cover_letter',
            field=models.TextField(help_text='Detailed explanation of how to execute the project', verbose_name='Cover Letter'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='estimated_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimated Hours'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='includes_materials',
            field=models.BooleanField(default=False, verbose_name='Includes Materials'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured proposal appears first', verbose_name='Featured Proposal'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='portfolio_samples',
            field=models.JSONField(blank=True, default=list, verbose_name='Portfolio Samples'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Professional'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='professional_completion_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Project Completion Rate'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='professional_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Professional Rating'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='professional_reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Reviews Count'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='projects.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rejection Reason'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Response Date'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='response_time',
            field=models.CharField(blank=True, help_text='e.g., within an hour', max_length=50, verbose_name='Response Time'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Proposal Status'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='timeline',
            field=models.CharField(help_text='e.g., 2-3 weeks', max_length=100, verbose_name='Timeline'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='warranty_period',
            field=models.CharField(blank=True, max_length=50, verbose_name='Warranty Period'),
        ),
        migrations.AlterField(
            model_name='proposalattachment',
            name='description',
            field=models.TextField(blank=True, verbose_name='File Description'),
        ),
        migrations.AlterField(
            model_name='proposalattachment',
            name='file',
            field=models.FileField(upload_to='proposal_attachments/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='proposalattachment',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size (bytes)'),
        ),
        migrations.AlterField(
            model_name='proposalattachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('other', 'Other')], default='document', max_length=20, verbose_name='File Type'),
        ),
        migrations.AlterField(
            model_name='proposalattachment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='proposalattachment',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments_files', to='proposals.proposal', verbose_name='Proposal'),
        ),
        migrations.AlterField(
            model_name='proposalmilestone',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Milestone Amount'),
        ),
        migrations.AlterField(
            model_name='proposalmilestone',
            name='description',
            field=models.TextField(blank=True, verbose_name='Milestone Description'),
        ),
        migrations.AlterField(
            model_name='proposalmilestone',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Milestone Order'),
        ),
        migrations.AlterField(
            model_name='proposalmilestone',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='proposals.proposal', verbose_name='Proposal'),
        ),
        migrations.AlterField(
            model_name='proposalmilestone',
            name='timeline',
            field=models.CharField(max_length=100, verbose_name='Milestone Duration'),
        ),
        migrations.AlterField(
            model_name='proposalmilestone',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Milestone Title'),
        ),
        migrations.AlterField(
            model_name='proposalview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='proposalview',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='proposals.proposal', verbose_name='Proposal'),
        ),
        migrations.AlterField(
            model_name='proposalview',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Viewer'),
        ),
    ]
