# Generated by Django 4.2.7 on 2025-07-23 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contractpayment'),
        ('proposals', '0002_alter_proposal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal', to='contracts.contract', verbose_name='Contract'),
        ),
    ]
