# Generated by Django 4.2.7 on 2025-07-23 23:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contracttimetracking_contracttask_contractlocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_type', models.CharField(choices=[('deposit', 'Deposit'), ('milestone', 'Milestone Payment'), ('final', 'Final Payment'), ('partial', 'Partial Payment'), ('refund', 'Refund')], default='partial', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('payment_provider', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('payment_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_payments', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Contract Payment',
                'verbose_name_plural': 'Contract Payments',
                'db_table': 'contract_payments',
                'ordering': ['-due_date'],
            },
        ),
    ]
