# Generated by Django 4.2.7 on 2025-07-24 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0003_contractpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('milestone', 'Milestone'), ('deadline', 'Deadline'), ('review', 'Review'), ('payment', 'Payment'), ('inspection', 'Inspection'), ('delivery', 'Delivery'), ('appointment', 'Appointment')], default='appointment', max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contract Calendar Event',
                'verbose_name_plural': 'Contract Calendar Events',
                'db_table': 'contract_calendar_events',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.RemoveField(
            model_name='contractcalendar',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='contractcalendar',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='contractpayment',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='contracttask',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='contracttask',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='contracttimetracking',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='contracttimetracking',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='contracttimetracking',
            name='professional',
        ),
        migrations.AlterModelOptions(
            name='contractlocation',
            options={'ordering': ['-is_primary', '-created_at'], 'verbose_name': 'Contract Location', 'verbose_name_plural': 'Contract Locations'},
        ),
        migrations.RemoveField(
            model_name='contractamendment',
            name='amount_change',
        ),
        migrations.RemoveField(
            model_name='contractamendment',
            name='timeline_change_days',
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='amendment_type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('change_order', 'Change Order'), ('extension', 'Extension'), ('modification', 'Modification'), ('cancellation', 'Cancellation')], default='appointment', max_length=20),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='cost_change',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost change amount (positive for increase, negative for decrease)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='meeting_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='timeline_change',
            field=models.PositiveIntegerField(blank=True, help_text='Timeline change in days', null=True),
        ),
        migrations.AlterField(
            model_name='contractamendment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contractamendment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='contractlocation',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='contractamendment',
            index=models.Index(fields=['contract'], name='contract_am_contrac_29b78a_idx'),
        ),
        migrations.AddIndex(
            model_name='contractamendment',
            index=models.Index(fields=['amendment_type'], name='contract_am_amendme_5fbdae_idx'),
        ),
        migrations.AddIndex(
            model_name='contractamendment',
            index=models.Index(fields=['status'], name='contract_am_status_23a168_idx'),
        ),
        migrations.AddIndex(
            model_name='contractamendment',
            index=models.Index(fields=['appointment_date'], name='contract_am_appoint_554187_idx'),
        ),
        migrations.DeleteModel(
            name='ContractCalendar',
        ),
        migrations.DeleteModel(
            name='ContractPayment',
        ),
        migrations.DeleteModel(
            name='ContractTask',
        ),
        migrations.DeleteModel(
            name='ContractTimeTracking',
        ),
        migrations.AddField(
            model_name='contractcalendarevent',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractcalendarevent',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='contracts.contract'),
        ),
        migrations.AddIndex(
            model_name='contractcalendarevent',
            index=models.Index(fields=['contract'], name='contract_ca_contrac_7ac880_idx'),
        ),
        migrations.AddIndex(
            model_name='contractcalendarevent',
            index=models.Index(fields=['date'], name='contract_ca_date_0f6306_idx'),
        ),
        migrations.AddIndex(
            model_name='contractcalendarevent',
            index=models.Index(fields=['event_type'], name='contract_ca_event_t_4b116f_idx'),
        ),
        migrations.AddIndex(
            model_name='contractcalendarevent',
            index=models.Index(fields=['status'], name='contract_ca_status_c52e0e_idx'),
        ),
    ]
