# Generated by Django 4.2.7 on 2025-07-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contractcalendarevent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractAmendment',
        ),
    ]
